eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-01412386.okta.com/oauth2/default
    client-id: 0oa8he3u1pMgHmUZH5d7
    client-secret: OO-1-B4z9V0udp6mSiXrhbtSEro7_qMsLCh3IFJZ
    audience: api://default
    scopes: profile, email, phone, offline_access, openid

message: Hello There!!  

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://13.232.33.119:9411/api/v2/spans

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true









      
